highlighter: rouge
relative_permalinks: false
url: https://mkesenheimer.github.io/mkesenheimer.github.io
title: Physik, Elektronik und mehr...
description: 
exclude: ["CNAME", "README", "bin", "build.xml"]
permalink: /news/:year/:month/:day/:title

author :
  name : Matthias Kesenheimer
  email : m.kesenheimer@gmx.net
  github : mkesenheimer

project:
  name: mkesenheimer
  github: mkesenheimer
